#!/usr/bin/env bash
set -u

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAMP="$(date -u +%Y%m%d-%H%M%S)"
OUT="$BASE_DIR/evidence/runtime-$STAMP"
mkdir -p "$OUT"

run() {
  local file="$1"
  shift
  {
    echo "=== Command: $* ==="
    echo "=== UTC: $(date -u --iso-8601=seconds) ==="
    "$@" 2>&1 || true
    echo
  } > "$OUT/$file"
}

run 01-host.txt bash -lc 'cat /etc/os-release; echo; uname -a; echo; nproc; echo; free -h; echo; df -h /'
run 02-openclaw.txt bash -lc 'command -v openclaw; openclaw --version; echo; systemctl is-active openclaw-gateway.service; echo; systemctl is-enabled openclaw-gateway.service'
run 03-docker.txt bash -lc 'docker version --format "{{.Server.Version}}" 2>/dev/null || docker version; echo; docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"; echo; docker network ls'
run 04-labs.txt bash -lc 'echo "--- Expected lab containers ---"; docker ps -a --filter name=webgoat --filter name=juice --filter name=vsftpd-lab --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"; echo; echo "--- VSFTPD local listeners ---"; ss -lnt 2>/dev/null | grep -E "127.0.0.1:(2121|6200)|:21|:6200" || true; echo; echo "--- Local VSFTPD TCP checks ---"; (nc -vz -w 2 127.0.0.1 2121 || true); (nc -vz -w 2 127.0.0.1 6200 || true)'
run 05-metasploit.txt bash -lc 'command -v msfconsole; msfconsole --version 2>&1 | head -n 5'
run 06-model-routing.txt bash -lc 'echo "Model routing is documented in docs/model-routing.md."; echo; grep -RhoE "(openrouter/free|google/gemini-3\.5-flash-lite|opencode/[a-zA-Z0-9._-]+-free|opencode/big-pickle)" "$BASE_DIR/configs" "$BASE_DIR/docs" 2>/dev/null | sort -u'
run 07-listeners.txt bash -lc 'echo "--- Listening TCP sockets (first 100 lines) ---"; ss -lnt 2>/dev/null | head -n 100'

cat > "$OUT/00-summary.txt" <<EOF
Cloud AI Cybersecurity Lab — Runtime Evidence Collection

UTC timestamp: $(date -u --iso-8601=seconds)
Evidence directory: $OUT

This bundle was generated by a read-only collection script.
Review every file before committing it.

No claim of exploit success is made by this collection.
EOF

echo "Evidence collection complete: $OUT"
echo "Review the files before committing."
