#!/usr/bin/env bash
set -u

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export BASE_DIR
STAMP="$(date -u +%Y%m%d-%H%M%S)"
OUT="$BASE_DIR/evidence/runtime-$STAMP"
mkdir -p "$OUT"

run() {
  local file="$1"
  shift
  {
    echo "=== Command: $* ==="
    echo "=== UTC: $(date -u --iso-8601=seconds) ==="
    "$@" 2>&1 || true
    echo
  } > "$OUT/$file"
}

run 01-host.txt bash -lc 'cat /etc/os-release; echo; uname -a; echo; nproc; echo; free -h; echo; df -h /'

run 02-openclaw.txt bash -lc '
echo "--- Version ---"
command -v openclaw || true
openclaw --version 2>&1 || true
echo
echo "--- Gateway process ---"
pgrep -af "openclaw.*gateway" || true
echo
echo "--- Gateway listeners ---"
ss -lntp 2>/dev/null | grep -E "127\.0\.0\.1:18789|172\.17\.0\.1:18789" || true
'

run 03-docker.txt bash -lc '
echo "--- Docker server ---"
docker version --format "{{.Server.Version}}" 2>/dev/null || docker version
echo
echo "--- Project containers ---"
docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}" |
grep -E "^(NAMES|vsftpd-lab|webgoat|juice-shop|open-webui)[[:space:]]" || true
'

run 04-labs.txt bash -lc '
echo "--- Lab containers ---"
docker ps -a --filter name=webgoat --filter name=juice-shop --filter name=vsftpd-lab \
  --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"

echo
echo "--- WebGoat host HTTP check ---"
curl -fsS -o /dev/null -w "HTTP %{http_code}\n" --max-time 5 http://127.0.0.1:8080/ || true

echo
echo "--- Juice Shop host HTTP check ---"
curl -fsS -o /dev/null -w "HTTP %{http_code}\n" --max-time 5 http://127.0.0.1:3001/ || true

echo
echo "--- Open WebUI published endpoint check ---"
WEBUI_ENDPOINT="$(docker port open-webui 8080/tcp 2>/dev/null | head -n 1 | sed "s/ -> /:/")"
if [ -n "$WEBUI_ENDPOINT" ]; then
  echo "Published endpoint: $WEBUI_ENDPOINT"
  curl -fsS -o /dev/null -w "HTTP %{http_code}\n" --max-time 5 "http://$WEBUI_ENDPOINT/" || true
else
  echo "Published endpoint: not detected"
fi

echo
echo "--- VSFTPD listeners ---"
ss -lnt 2>/dev/null | grep -E "127\.0\.0\.1:(2121|6200)" || true

echo
echo "--- VSFTPD TCP checks ---"
nc -vz -w 2 127.0.0.1 2121 || true
nc -vz -w 2 127.0.0.1 6200 || true
'

run 05-metasploit.txt bash -lc 'command -v msfconsole; msfconsole --version 2>&1 | head -n 5'

run 06-model-routing.txt bash -lc '
echo "--- Documented model routing identifiers ---"
grep -RhoE "(openrouter/free|google/gemini-3\.5-flash-lite|opencode/[a-zA-Z0-9._-]+-free|opencode/big-pickle)" "$BASE_DIR/configs" "$BASE_DIR/docs" 2>/dev/null | sort -u
'

run 07-listeners.txt bash -lc '
echo "--- Project-relevant listeners only ---"
ss -lnt 2>/dev/null |
grep -E "127\.0\.0\.1:(18789|2121|3001|3000|5433|6200|8080|11434)|172\.17\.0\.1:18789" || true
'

cat > "$OUT/00-summary.txt" <<EOF
Cloud AI Cybersecurity Lab — Runtime Evidence Collection

UTC timestamp: $(date -u --iso-8601=seconds)
Evidence directory: $OUT

This bundle was generated by a read-only collection script.
It records runtime observations only; it does not claim exploit success.

Review every file before committing.
EOF

echo "Evidence collection complete: $OUT"
echo "Review the files before committing."
